const mongoose = require("mongoose");

const DEFAULT_FEATURE_FLAGS = [
  // ── 1. LEAD GENERATION & DATA DISCOVERY ──
  {
    key: "companies",
    title: "Companies Catalog",
    category: "lead_gen",
    categoryLabel: "Data",
    description: "Search 1.5M+ B2B companies with phone numbers, domains, categories and locations.",
    path: "/app/companies",
    icon: "Building2",
    status: "enabled",
    badge: "",
    order: 10,
  },
  {
    key: "people",
    title: "People Directory",
    category: "lead_gen",
    categoryLabel: "Data",
    description: "Access 45M+ professional profiles with job titles, verified phones and location data.",
    path: "/app/people",
    icon: "Users2",
    status: "enabled",
    badge: "POPULAR",
    order: 20,
  },
  {
    key: "emails",
    title: "Direct Emails Finder",
    category: "lead_gen",
    categoryLabel: "Data",
    description: "Query and extract verified corporate and personal emails.",
    path: "/app/email",
    icon: "Mail",
    status: "enabled",
    badge: "",
    order: 30,
  },
  {
    key: "numbers",
    title: "Phone Numbers Finder",
    category: "lead_gen",
    categoryLabel: "Data",
    description: "Filter direct mobile numbers and business phone contacts.",
    path: "/app/number",
    icon: "Phone",
    status: "enabled",
    badge: "",
    order: 40,
  },
  {
    key: "categories",
    title: "Category Explorer",
    category: "lead_gen",
    categoryLabel: "Data",
    description: "Explore 500+ business categories and industry verticals.",
    path: "/app/categories",
    icon: "Grid3x3",
    status: "enabled",
    badge: "",
    order: 50,
  },
  {
    key: "cities",
    title: "City & Region Explorer",
    category: "lead_gen",
    categoryLabel: "Data",
    description: "Geographic search by state, city, and district across India & Global.",
    path: "/app/cities",
    icon: "MapPin",
    status: "enabled",
    badge: "",
    order: 60,
  },
  {
    key: "inbuild_db",
    title: "In-Build Database",
    category: "lead_gen",
    categoryLabel: "Data",
    description: "Explore pre-loaded structured datasets with instant export.",
    path: "/app/inbuild-db",
    icon: "Database",
    status: "enabled",
    badge: "",
    order: 70,
  },
  {
    key: "db_intelligence",
    title: "Database Intelligence",
    category: "lead_gen",
    categoryLabel: "Data",
    description: "Deep statistical breakdowns and query analytics on company cohorts.",
    path: "/app/db-intelligence",
    icon: "Sparkles",
    status: "enabled",
    badge: "PRO",
    order: 80,
  },
  {
    key: "india_data",
    title: "India B2B Master Data",
    category: "lead_gen",
    categoryLabel: "Data",
    description: "Dedicated pan-India company, director, and decision maker directory.",
    path: "/app/india-data",
    icon: "Globe",
    status: "enabled",
    badge: "",
    order: 90,
  },
  {
    key: "public_data",
    title: "Public Contacts Catalog",
    category: "lead_gen",
    categoryLabel: "Data",
    description: "Public business registers and domain-linked contacts.",
    path: "/app/public-data",
    icon: "Contact",
    status: "enabled",
    badge: "",
    order: 100,
  },
  {
    key: "lg_linkedin",
    title: "LinkedIn Prospector",
    category: "lead_gen",
    categoryLabel: "Data",
    description: "Find verified LinkedIn URLs and decision maker profiles.",
    path: "/app/lg/linkedin",
    icon: "Linkedin",
    status: "enabled",
    badge: "HOT",
    order: 110,
  },
  {
    key: "lg_email",
    title: "Email Pattern Matcher",
    category: "lead_gen",
    categoryLabel: "Data",
    description: "Predict company email formats (e.g. first.last@domain.com).",
    path: "/app/lg/email",
    icon: "AtSign",
    status: "enabled",
    badge: "",
    order: 120,
  },
  {
    key: "lg_companies",
    title: "Company Intelligence",
    category: "lead_gen",
    categoryLabel: "Data",
    description: "Comprehensive firmographic intel, revenue range, and tech stack.",
    path: "/app/lg/companies",
    icon: "Briefcase",
    status: "enabled",
    badge: "",
    order: 130,
  },
  {
    key: "lg_auto_lead_gen",
    title: "Autonomous Lead Generator",
    category: "lead_gen",
    categoryLabel: "Data",
    description: "AI-powered automated lead list synthesis based on prompt criteria.",
    path: "/app/lg/auto-lead-gen",
    icon: "Zap",
    status: "enabled",
    badge: "AI",
    order: 140,
  },

  // ── 2. AI & AUTOMATION ──
  {
    key: "chatbot",
    title: "Ask Doott AI",
    category: "ai_automation",
    categoryLabel: "AI & Automation",
    description: "AI conversational assistant with contextual knowledge retrieval.",
    path: "/app/chatbot",
    icon: "MessageSquare",
    status: "enabled",
    badge: "AI",
    order: 200,
  },
  {
    key: "chatbot_data",
    title: "AI Knowledge Base & Data",
    category: "ai_automation",
    categoryLabel: "AI & Automation",
    description: "Upload PDFs, documents, and FAQs to train custom organization chatbots.",
    path: "/app/chatbot/data",
    icon: "BookOpen",
    status: "enabled",
    badge: "",
    order: 210,
  },
  {
    key: "autonomous_agents",
    title: "Autonomous SDR Agents",
    category: "ai_automation",
    categoryLabel: "AI & Automation",
    description: "Deploy autonomous sales agents to discover, enrich, and contact leads.",
    path: "/app/autonomousagents",
    icon: "Bot",
    status: "enabled",
    badge: "BETA",
    order: 220,
  },
  {
    key: "lg_research",
    title: "AI Deep Research Agent",
    category: "ai_automation",
    categoryLabel: "AI & Automation",
    description: "Autonomous agent for company research, competitive analysis, and summaries.",
    path: "/app/lg/research",
    icon: "Cpu",
    status: "enabled",
    badge: "AI",
    order: 230,
  },

  // ── 3. WEB SCRAPING & CRAWLERS ──
  {
    key: "places_scraper",
    title: "Google Maps / Places Scraper",
    category: "crawlers",
    categoryLabel: "Scrapers & Crawlers",
    description: "Scrape local businesses, reviews, phone numbers, and ratings from Google Places.",
    path: "/app/places",
    icon: "MapPin",
    status: "enabled",
    badge: "",
    order: 300,
  },
  {
    key: "websites_crawler",
    title: "Website Deep Scraper",
    category: "crawlers",
    categoryLabel: "Scrapers & Crawlers",
    description: "Crawl target websites for contact info, emails, and social links.",
    path: "/app/websites",
    icon: "Globe2",
    status: "enabled",
    badge: "",
    order: 310,
  },
  {
    key: "auto_scraper",
    title: "Scheduled Auto-Scraper",
    category: "crawlers",
    categoryLabel: "Scrapers & Crawlers",
    description: "Automate recurring scheduled scraping tasks with cloud webhooks.",
    path: "/app/auto-scraper",
    icon: "Search",
    status: "enabled",
    badge: "",
    order: 320,
  },
  {
    key: "crawler",
    title: "Live URL Web Crawler",
    category: "crawlers",
    categoryLabel: "Scrapers & Crawlers",
    description: "Real-time web crawler with DOM parsing and extraction.",
    path: "/app/crawler",
    icon: "Compass",
    status: "enabled",
    badge: "",
    order: 330,
  },

  // ── 4. OUTREACH & SOCIAL MARKETING ──
  {
    key: "social_media",
    title: "Social Media Automation",
    category: "outreach_social",
    categoryLabel: "Outreach & Social",
    description: "Multi-platform auto-posting to LinkedIn, Twitter, Instagram, and Facebook.",
    path: "/app/social",
    icon: "Share2",
    status: "enabled",
    badge: "",
    order: 400,
  },
  {
    key: "smart_outreach",
    title: "Smart Email Outreach",
    category: "outreach_social",
    categoryLabel: "Outreach & Social",
    description: "AI-personalized cold email campaigns with SMTP and Gmail integrations.",
    path: "/app/outreach",
    icon: "Send",
    status: "enabled",
    badge: "",
    order: 410,
  },
  {
    key: "pipeline",
    title: "Sales Pipeline Tracker",
    category: "outreach_social",
    categoryLabel: "Outreach & Social",
    description: "Visual stage-by-stage sales funnel and conversion tracker.",
    path: "/app/pipeline",
    icon: "GitBranch",
    status: "enabled",
    badge: "",
    order: 420,
  },
  {
    key: "icp",
    title: "ICP Targeting Engine",
    category: "outreach_social",
    categoryLabel: "Outreach & Social",
    description: "Define Ideal Customer Profiles and auto-score matched prospects.",
    path: "/app/icp",
    icon: "Target",
    status: "enabled",
    badge: "",
    order: 430,
  },
  {
    key: "scheduler",
    title: "Campaign Scheduler",
    category: "outreach_social",
    categoryLabel: "Outreach & Social",
    description: "Schedule automated pipeline phases, enrichment, and outreach runs.",
    path: "/app/scheduler",
    icon: "Calendar",
    status: "enabled",
    badge: "",
    order: 440,
  },
  {
    key: "sheets",
    title: "Google Sheets Live Sync",
    category: "outreach_social",
    categoryLabel: "Outreach & Social",
    description: "Two-way live synchronization between Doott leads and Google Sheets.",
    path: "/app/sheets",
    icon: "FileSpreadsheet",
    status: "enabled",
    badge: "",
    order: 450,
  },
  {
    key: "leads",
    title: "My Leads Vault",
    category: "outreach_social",
    categoryLabel: "Outreach & Social",
    description: "Centralized bookmarking and export hub for saved prospects.",
    path: "/app/leads",
    icon: "Bookmark",
    status: "enabled",
    badge: "",
    order: 460,
  },

  // ── 5. CRM SUITE ──
  {
    key: "crm_dashboard",
    title: "CRM Analytics Dashboard",
    category: "crm_suite",
    categoryLabel: "CRM Suite",
    description: "Executive KPIs, revenue forecasting, deal conversion rates, and metrics.",
    path: "/app/crm/dashboard",
    icon: "BarChart3",
    status: "enabled",
    badge: "",
    order: 500,
  },
  {
    key: "crm_pipeline",
    title: "Deals Kanban Pipeline",
    category: "crm_suite",
    categoryLabel: "CRM Suite",
    description: "Drag-and-drop Kanban board for managing deals across sales stages.",
    path: "/app/crm/pipeline",
    icon: "Kanban",
    status: "enabled",
    badge: "",
    order: 510,
  },
  {
    key: "crm_activities",
    title: "Activities & Tasks",
    category: "crm_suite",
    categoryLabel: "CRM Suite",
    description: "Log calls, meetings, tasks, and follow-ups with team members.",
    path: "/app/crm/activities",
    icon: "CheckSquare",
    status: "enabled",
    badge: "",
    order: 520,
  },
  {
    key: "crm_quotations",
    title: "Quotations & Estimates",
    category: "crm_suite",
    categoryLabel: "CRM Suite",
    description: "Generate and send professional PDF quotations with custom pricing.",
    path: "/app/crm/quotations",
    icon: "FileText",
    status: "enabled",
    badge: "",
    order: 530,
  },
  {
    key: "crm_invoices",
    title: "Invoices & Billing",
    category: "crm_suite",
    categoryLabel: "CRM Suite",
    description: "Create, track, and send invoices with tax calculations and payment status.",
    path: "/app/crm/invoices",
    icon: "Receipt",
    status: "enabled",
    badge: "",
    order: 540,
  },

  // ── 6. ERP SUITE ──
  {
    key: "accounting",
    title: "General Ledger & Accounting",
    category: "erp_suite",
    categoryLabel: "ERP Suite",
    description: "Double-entry bookkeeping, chart of accounts, and financial reports.",
    path: "/app/accounting",
    icon: "Calculator",
    status: "enabled",
    badge: "ENTERPRISE",
    order: 600,
  },
  {
    key: "inventory",
    title: "Inventory & Stock Control",
    category: "erp_suite",
    categoryLabel: "ERP Suite",
    description: "Track SKU quantities, reorder points, warehouses, and valuations.",
    path: "/app/inventory",
    icon: "Package",
    status: "enabled",
    badge: "ENTERPRISE",
    order: 610,
  },
  {
    key: "payroll",
    title: "Payroll & Salaries",
    category: "erp_suite",
    categoryLabel: "ERP Suite",
    description: "Process monthly salaries, deductions, taxes, and payslips.",
    path: "/app/payroll",
    icon: "DollarSign",
    status: "enabled",
    badge: "ENTERPRISE",
    order: 620,
  },

  // ── 7. SYSTEM & PLATFORM ──
  {
    key: "docs",
    title: "Documentation & Guides",
    category: "system",
    categoryLabel: "System",
    description: "Platform guides, API documentation, and tutorials.",
    path: "/app/docs",
    icon: "BookMarked",
    status: "enabled",
    badge: "",
    order: 700,
  },
  {
    key: "settings",
    title: "Organization Settings",
    category: "system",
    categoryLabel: "System",
    description: "Manage organization details, members, integrations, and preferences.",
    path: "/app/settings",
    icon: "Settings",
    status: "enabled",
    badge: "",
    order: 710,
  },
  {
    key: "admin",
    title: "Admin Control Center",
    category: "system",
    categoryLabel: "System",
    description: "Owner-only dashboard for feature toggles, platform telemetry, and traffic.",
    path: "/app/admin",
    icon: "ShieldCheck",
    status: "admin_only",
    badge: "OWNER",
    order: 720,
  }
];

const featureFlagSchema = new mongoose.Schema(
  {
    key: {
      type: String,
      required: true,
      unique: true,
      trim: true,
      lowercase: true,
      index: true,
    },
    title: {
      type: String,
      required: true,
      trim: true,
    },
    category: {
      type: String,
      required: true,
      enum: ["lead_gen", "ai_automation", "crawlers", "outreach_social", "crm_suite", "erp_suite", "system"],
      index: true,
    },
    categoryLabel: {
      type: String,
      default: "General",
    },
    description: {
      type: String,
      default: "",
    },
    path: {
      type: String,
      required: true,
    },
    icon: {
      type: String,
      default: "Layers",
    },
    status: {
      type: String,
      enum: ["enabled", "disabled", "admin_only"],
      default: "enabled",
      index: true,
    },
    badge: {
      type: String,
      default: "",
      trim: true,
    },
    order: {
      type: Number,
      default: 100,
    },
    updatedBy: {
      type: String,
      default: "system",
    },
  },
  {
    timestamps: true,
    versionKey: false,
  }
);

// Helper static method to initialize defaults if missing
featureFlagSchema.statics.ensureDefaults = async function () {
  const count = await this.countDocuments();
  if (count === 0) {
    await this.insertMany(DEFAULT_FEATURE_FLAGS);
    return;
  }
  
  // Upsert any newly defined default flags that might not exist yet
  const ops = DEFAULT_FEATURE_FLAGS.map(flag => ({
    updateOne: {
      filter: { key: flag.key },
      update: { $setOnInsert: flag },
      upsert: true,
    }
  }));
  if (ops.length > 0) {
    await this.bulkWrite(ops);
  }
};

const FeatureFlag = mongoose.models.FeatureFlag || mongoose.model("FeatureFlag", featureFlagSchema);

module.exports = {
  FeatureFlag,
  DEFAULT_FEATURE_FLAGS,
};
